spring:
  gateway:
    discovery:
      locator:
        enabled: true
        lower-case-service-id: true
#  sleuth:
#    sampler:
#      probability: 1.0


management:
  endpoints:
    web:
      exposure:
        include: gateway


# http://localhost:8765/service-another-micro-dude/service1/feign-bla
# http://localhost:8765/service-micro-dude-kman/consume-me
# http://localhost:8765/get